2025-09-13 23:15:43,157 [WARNING] PyNaCl is not installed, voice will NOT be supported
2025-09-13 23:15:43,158 [INFO] logging in using static token
2025-09-13 23:15:44,337 [CRITICAL] Botの実行中に予期せぬエラーが発生しました。
Traceback (most recent call last):
  File "/home/yuki-chiba/duplicate-checker-bot/bot.py", line 115, in <module>
    client.run(TOKEN)
  File "/home/yuki-chiba/duplicate-checker-bot/venv/lib/python3.12/site-packages/discord/client.py", line 929, in run
    asyncio.run(runner())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/yuki-chiba/duplicate-checker-bot/venv/lib/python3.12/site-packages/discord/client.py", line 918, in runner
    await self.start(token, reconnect=reconnect)
  File "/home/yuki-chiba/duplicate-checker-bot/venv/lib/python3.12/site-packages/discord/client.py", line 847, in start
    await self.connect(reconnect=reconnect)
  File "/home/yuki-chiba/duplicate-checker-bot/venv/lib/python3.12/site-packages/discord/client.py", line 771, in connect
    raise PrivilegedIntentsRequired(exc.shard_id) from None
discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.
2025-09-13 23:17:44,232 [WARNING] PyNaCl is not installed, voice will NOT be supported
2025-09-13 23:17:44,233 [INFO] logging in using static token
2025-09-13 23:17:45,637 [CRITICAL] Botの実行中に予期せぬエラーが発生しました。
Traceback (most recent call last):
  File "/home/yuki-chiba/duplicate-checker-bot/bot.py", line 115, in <module>
    client.run(TOKEN)
  File "/home/yuki-chiba/duplicate-checker-bot/venv/lib/python3.12/site-packages/discord/client.py", line 929, in run
    asyncio.run(runner())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/yuki-chiba/duplicate-checker-bot/venv/lib/python3.12/site-packages/discord/client.py", line 918, in runner
    await self.start(token, reconnect=reconnect)
  File "/home/yuki-chiba/duplicate-checker-bot/venv/lib/python3.12/site-packages/discord/client.py", line 847, in start
    await self.connect(reconnect=reconnect)
  File "/home/yuki-chiba/duplicate-checker-bot/venv/lib/python3.12/site-packages/discord/client.py", line 771, in connect
    raise PrivilegedIntentsRequired(exc.shard_id) from None
discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.
2025-09-13 23:19:37,352 [WARNING] PyNaCl is not installed, voice will NOT be supported
2025-09-13 23:19:37,353 [INFO] logging in using static token
2025-09-13 23:19:38,687 [INFO] Shard ID None has connected to Gateway (Session ID: 9d861cc04464dacca9ee88475eead109).
2025-09-13 23:19:40,732 [INFO] データベースの準備が完了しました。
2025-09-13 23:19:40,732 [INFO] 画像重複判定bor#3274 としてログインしました。
2025-09-13 23:19:40,732 [INFO] ---------------------------------
2025-09-13 23:19:53,107 [INFO] 新規画像としてDBに登録しました: https://cdn.discordapp.com/attachments/959482025444794431/1416428169006813275/IMG_0592.jpg?ex=68c6cf07&is=68c57d87&hm=d7b61490cd4c067058a12704ead966897427753aa6d98a78bda7596eb70d937a&
2025-09-13 23:19:58,075 [INFO] 重複検出: https://cdn.discordapp.com/attachments/959482025444794431/1416428189806493787/IMG_0592.jpg?ex=68c6cf0c&is=68c57d8c&hm=ee673a7e693783ab2f3b45af91416ef433c40b54ca5a3f9782ff47a1d344b383& は https://discord.com/channels/959482025444794428/959482025444794431/1416428169254146178 と類似しています。
2025-09-13 23:51:10,817 [WARNING] PyNaCl is not installed, voice will NOT be supported
2025-09-13 23:51:10,818 [INFO] logging in using static token
2025-09-13 23:51:12,176 [INFO] Shard ID None has connected to Gateway (Session ID: 5f5323df7dda63ddf39773d2ffa6b950).
2025-09-13 23:51:14,205 [INFO] URLデータベースの準備が完了しました。
2025-09-13 23:51:14,206 [INFO] 画像重複判定bor#3274 (URL Checker) としてログインしました。
2025-09-13 23:52:38,241 [INFO] 新規URLを登録: https://x.com/xdeyuix/status/1966465674101854383?s=46
2025-09-13 23:53:04,472 [INFO] 重複URLを検出: https://x.com/xdeyuix/status/1966465674101854383?s=46
2025-09-13 23:53:33,610 [INFO] 新規URLを登録: https://x.com/ugjk0925/status/1966845656150254050?s=46
2025-09-13 23:55:28,112 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/yuki-chiba/duplicate-checker-bot/venv/lib/python3.12/site-packages/discord/client.py", line 504, in _run_event
    await coro(*args, **kwargs)
  File "/home/yuki-chiba/duplicate-checker-bot/bot.py", line 84, in on_message
    await message.reply(f"このURLは過去に投稿されています！\n{duplicate_message_url}")
  File "/home/yuki-chiba/duplicate-checker-bot/venv/lib/python3.12/site-packages/discord/message.py", line 1879, in reply
    return await self.channel.send(content, reference=self, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yuki-chiba/duplicate-checker-bot/venv/lib/python3.12/site-packages/discord/abc.py", line 1703, in send
    data = await state.http.send_message(channel.id, params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yuki-chiba/duplicate-checker-bot/venv/lib/python3.12/site-packages/discord/http.py", line 773, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In message_reference: Unknown message
2025-09-13 23:55:37,933 [INFO] 重複URLを検出: https://x.com/ugjk0925/status/1966845656150254050?s=46
2025-09-13 23:55:49,463 [INFO] 重複URLを検出: https://x.com/ugjk0925/status/1966845656150254050?s=46
2025-09-13 23:59:31,910 [INFO] 新規URLを登録: https://x.com/refi0429/status/1966803965728919846?s=46
2025-09-13 23:59:36,177 [INFO] 重複URLを検出: https://x.com/refi0429/status/1966803965728919846?s=46
